version: "3"
services:
  database:
    image: postgres:11.6-alpine
    environment:
      - POSTGRES_USER=hedgedoc
      - POSTGRES_PASSWORD=change_password
      - POSTGRES_DB=hedgedoc
    volumes:
      - "./data/database-data:/var/lib/postgresql/data"
    restart: always
  hedgedoc:
    image: yoneyan/hedgedoc:0.1
    #build:
    #  context: .
    #  dockerfile: ./Dockerfile
    environment:
      - CMD_DB_URL=postgres://hedgedoc:change_password@database/hedgedoc
      - CMD_ALLOW_ANONYMOUS=true
      - CMD_ALLOW_ANONYMOUS_EDITS=true
      - CMD_USECDN=false
      - CMD_DOMAIN=172.50.1.161:3000
      - CMD_IMAGE_UPLOAD_TYPE=filesystem
      - CMD_URL_ADD_PORT=true
      - CMD_SESSION_NAME=connect.codimd.sid
      - GROWI_URI=http://172.29.0.1:5000
    depends_on:
      - database
    ports:
      - "3000:3000"
    volumes:
      - ./data/upload-data:/opt/hedgedoc/public/uploads
    restart: always
