version: '3'

services:
  ldap1:
    build: ./openldap
    image: kushimoto/openldap:latest
    restart: always
    container_name: ldap1
    environment:
      LDAP_ORGANISATION: "doornoc"
      LDAP_BASE_DN: "dc=local,dc=doornoc,dc=net"
      # LDAP_DOMAIN: "local.doornoc.net"
      LDAP_ADMIN_PASSWORD: "password" #cn=admin,dc=hogetech,dc=com のパスワード
      LDAP_CONFIG_PASSWORD: "password" #cn=admin,cn=config のパスワード
    networks:
      - webnet
    # ports:
    # - "389:389"
    #  - "636:636"

  ldap2:
    build: ./openldap
    image: kushimoto/openldap:latest
    restart: always
    container_name: ldap2
    environment:
      LDAP_ORGANISATION: "doornoc"
      LDAP_BASE_DN: "dc=local,dc=doornoc,dc=net"
      # LDAP_DOMAIN: "local.doornoc.net"
      LDAP_ADMIN_PASSWORD: "password" #cn=admin,dc=hogetech,dc=com のパスワード
      LDAP_CONFIG_PASSWORD: "password" #cn=admin,cn=config のパスワード
    networks:
      - webnet
    # ports:
    #  - "389:389"
    #  - "636:636"

  ldap-admin-primary:
    image: osixia/phpldapadmin:latest
    restart: always
    container_name: ldap-admin-primary
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "ldap"
      PHPLDAPADMIN_HTTPS: "false"
    ports:
      - "8080:80"
    links:
      - "ldap1:ldap"
    networks:
      - webnet

  ldap-admin-secondary:
    image: osixia/phpldapadmin:latest
    restart: always
    container_name: ldap-admin-secondary
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "ldap"
      PHPLDAPADMIN_HTTPS: "false"
    ports:
      - "8088:80"
    links:
      - "ldap2:ldap"
    networks:
      - webnet

networks:
  webnet:
