version: '3.7'

services:
  openldap:
    build: ./openldap
    image: kushimoto/openldap:latest
    restart: always
    container_name: openldap
    environment:
      LDAP_ORGANISATION: "doornoc"
      LDAP_BASE_DN: "dc=local,dc=doornoc,dc=net"
      LDAP_MANAGER_PASSWORD: "password" #cn=admin,dc=hogetech,dc=com のパスワード
      LDAP_CONFIG_PASSWORD: "password" #cn=admin,cn=config のパスワード
      LDAP_SERVER_ID: "101"
      LDAP_NEIGHBOR_ADDRESS: "neighbor_address"
    networks:
      - webnet
    ports:
    - "389:389"
    - "636:636"
    volumes:
      - openldap-data:/var/lib/openldap/openldap-data

  phpldapadmin:
    image: osixia/phpldapadmin:latest
    restart: always
    container_name: phpldapadmin
    environment:
      PHPLDAPADMIN_LDAP_CLIENT_TLS: false
      PHPLDAPADMIN_HTTPS: false
      PHPLDAPADMIN_LDAP_HOSTS: "#PYTHON2BASH:[{'openldap': [{'server': [{'tls': False},{'base': \"array('dc=local,dc=doornoc,dc=net', 'cn=config')\"}]}]}]"
    ports:
      - "8080:80"
    links:
      - "openldap:ldap"
    networks:
      - webnet

networks:
  webnet:

volumes:
  openldap-data:
