version: '3'

services:
  app:
    # build:
    #   context: .
    #   dockerfile: ./Dockerfile
    image: yoneyan/growi:0.1
    ports:
       #- 127.0.0.1:3000:3000    # localhost only by default
      - 5000:3000
    links:
      - mongo:mongo
      - elasticsearch:elasticsearch
    depends_on:
      - mongo
      - elasticsearch
    environment:
      - MONGO_URI=mongodb://mongo:27017/growi
      - ELASTICSEARCH_URI=http://elasticsearch:9200/growi
      - PASSWORD_SEED=changeme
      - FILE_UPLOAD=mongodb   # activate this line if you use MongoDB GridFS rather than AWS
      # - FILE_UPLOAD=local     # activate this line if you use local storage of server rather than AWS
      - MATHJAX=1             # activate this line if you want to use MathJax
      # - PLANTUML_URI=http://  # activate this line and specify if you use your own PlantUML server rather than public plantuml.com
      # - HACKMD_URI=http://localhost:3000    # activate this line and specify HackMD server URI which can be accessed from GROWI client browsers
      # - HACKMD_URI_FOR_SERVER=http://172.27.0.1:3000  # activate this line and specify HackMD server URI which can be accessed from this server container
      # - FORCE_WIKI_MODE='public'    # activate this line to force wiki public mode
      # - FORCE_WIKI_MODE='private'   # activate this line to force wiki private mode

    restart: unless-stopped
    volumes:
      - ./data/growi-data:/data

  mongo:
    image: mongo:4.4
    restart: unless-stopped
    volumes:
      - ./data/mongo-config:/data/configdb
      - ./data/mongo-data:/data/db

#  elasticsearch:
#    build:
#      context: ./elasticsearch
#      dockerfile: ./Dockerfile
#      args:
#        UID: 1000
#        GID: 1000
#    environment:
#      - bootstrap.memory_lock=true
#      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
#    ulimits:
#      memlock:
#        soft: -1
#        hard: -1
#    restart: unless-stopped
#    ports:
#      - 9200:9200
#      - 9300:9300
#    volumes:
#      - ./data/elasticsearch-data:/data